"""Write GUI-loadable Optiverse scene JSON from headless layouts."""

from __future__ import annotations

import copy
import json
import uuid
from dataclasses import asdict
from pathlib import Path
from typing import Any

from optiverse.core.models import SourceParams

from .catalog import Catalog
from .compiler import interfaces_for_placement, rotate_translate
from .schema import GoalSpec, Placement, SourceSpec

SCENE_VERSION = "2.0"
UUID_NAMESPACE = uuid.UUID("90a8eb5e-0e7e-4e77-88b4-8a4302f5d314")


def deterministic_uuid(*parts: object) -> str:
    """Create a stable UUID for generated scene items."""
    key = "::".join(str(part) for part in parts)
    return str(uuid.uuid5(UUID_NAMESPACE, key))


def source_to_scene_item(source: SourceSpec | SourceParams, goal_id: str) -> dict[str, Any]:
    """Serialize a source into the assembly item format expected by the GUI."""
    if isinstance(source, SourceSpec):
        data = source.to_dict()
    else:
        data = asdict(SourceSpec.from_source_params(source))
    data["_type"] = "source"
    data["item_uuid"] = deterministic_uuid(goal_id, "source")
    return data


def placement_to_scene_item(
    catalog: Catalog, placement: Placement, goal_id: str
) -> dict[str, Any]:
    """Serialize one placement into the GUI's component item format."""
    component = copy.deepcopy(catalog[placement.catalog_id])
    interfaces = interfaces_for_placement(catalog, placement)
    x_mm, y_mm = _gui_component_origin(interfaces, placement)

    component.update(
        {
            "_type": "component",
            "item_uuid": deterministic_uuid(goal_id, placement.label),
            "x_mm": x_mm,
            "y_mm": y_mm,
            "angle_deg": placement.angle_deg,
            "interfaces": interfaces,
            "notes": f"Generated by agentic layout harness as {placement.label}",
        }
    )
    component.pop("_catalog_id", None)
    return component


def _gui_component_origin(
    interfaces: list[dict[str, Any]], placement: Placement
) -> tuple[float, float]:
    """Return the GUI item origin matching ComponentItem's interface-reference origin.

    The headless compiler treats placement.x/y as the component definition's image-center
    origin. ComponentItem, however, sets the QGraphicsItem origin at the first interface's
    midpoint so sprites can be centered on their picked optical line. Convert here so the
    GUI's live retrace sees the same interface positions that the headless CLI scored.
    """
    if not interfaces:
        return placement.x_mm, placement.y_mm

    first = interfaces[0]
    midpoint_x = 0.5 * (float(first["x1_mm"]) + float(first["x2_mm"]))
    midpoint_y = 0.5 * (float(first["y1_mm"]) + float(first["y2_mm"]))
    return rotate_translate(midpoint_x, midpoint_y, placement)


def build_scene_data(catalog: Catalog, goal: GoalSpec) -> dict[str, Any]:
    """Build a version 2.0 Optiverse scene dictionary."""
    items = [source_to_scene_item(goal.source, goal.goal_id)]
    items.extend(
        placement_to_scene_item(catalog, placement, goal.goal_id)
        for placement in goal.placements
    )
    return {
        "version": SCENE_VERSION,
        "items": items,
        "rulers": [],
        "texts": [],
        "rectangles": [],
        "path_measures": [],
        "layer_state": {},
    }


def write_json(path: Path, data: Any) -> None:
    """Write deterministic pretty JSON with a trailing newline."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
