"""Write GUI-loadable Optiverse scene JSON from headless layouts."""

from __future__ import annotations

import copy
import json
import uuid
from dataclasses import asdict
from pathlib import Path
from typing import Any

from optiverse.core.models import SourceParams

from .catalog import Catalog
from .compiler import interfaces_for_placement
from .schema import GoalSpec, Placement, SourceSpec

SCENE_VERSION = "2.0"
UUID_NAMESPACE = uuid.UUID("90a8eb5e-0e7e-4e77-88b4-8a4302f5d314")


def deterministic_uuid(*parts: object) -> str:
    """Create a stable UUID for generated scene items."""
    key = "::".join(str(part) for part in parts)
    return str(uuid.uuid5(UUID_NAMESPACE, key))


def source_to_scene_item(source: SourceSpec | SourceParams, goal_id: str) -> dict[str, Any]:
    """Serialize a source into the assembly item format expected by the GUI."""
    if isinstance(source, SourceSpec):
        data = source.to_dict()
    else:
        data = asdict(SourceSpec.from_source_params(source))
    data["_type"] = "source"
    data["item_uuid"] = deterministic_uuid(goal_id, "source")
    return data


def placement_to_scene_item(
    catalog: Catalog, placement: Placement, goal_id: str
) -> dict[str, Any]:
    """Serialize one placement into the GUI's component item format."""
    component = copy.deepcopy(catalog[placement.catalog_id])
    interfaces = interfaces_for_placement(catalog, placement)

    component.update(
        {
            "_type": "component",
            "item_uuid": deterministic_uuid(goal_id, placement.label),
            "x_mm": placement.x_mm,
            "y_mm": placement.y_mm,
            "angle_deg": placement.angle_deg,
            "interfaces": interfaces,
            "notes": f"Generated by agentic layout harness as {placement.label}",
        }
    )
    component.pop("_catalog_id", None)
    return component


def build_scene_data(catalog: Catalog, goal: GoalSpec) -> dict[str, Any]:
    """Build a version 2.0 Optiverse scene dictionary."""
    items = [source_to_scene_item(goal.source, goal.goal_id)]
    items.extend(
        placement_to_scene_item(catalog, placement, goal.goal_id)
        for placement in goal.placements
    )
    return {
        "version": SCENE_VERSION,
        "items": items,
        "rulers": [],
        "texts": [],
        "rectangles": [],
        "path_measures": [],
        "layer_state": {},
    }


def write_json(path: Path, data: Any) -> None:
    """Write deterministic pretty JSON with a trailing newline."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
